version: "3"

networks:
  laravel:

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    container_name: app_simple_pointer
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  supervisor:
    build:
      context: .
      dockerfile: ./.docker/supervisor/Dockerfile
    container_name: supervisor
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - app
    ports:
      - "6001:6001"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public:delegated
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

    # if you are developing on a Linux server you might want these to help run tests
    # modified instructions from here: https://medium.com/@scuttlebyte/running-headless-laravel-dusk-3-0-tests-in-docker-environments-f396752a9ffe
  selenium:
    image: selenium/standalone-chrome
    depends_on:
      - app
    # used shared memory to run as opposed to assuming /dev/shm is there to be mounted
    shm_size: '2gb'
    container_name: selenium
    ports:
      - "4444:4444"
    links:
      - nginx:planningpoker.test
    # how I want to find the webserver
    networks:
      - laravel
